### ISSUE TITLE
Compilations / various artist albums are created as separate albums

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#1]
**Describe the issue**
received from a beta tester: "No matter how I tag an album, unless all the artists are the same, you end up with 20 separate albums. [...] [then] you can't use the track skip buttons unless you've selected 'play all' and, in the scenario above, you can never select play all because each album only has one track in it."

**AudioWagon version**
0.2.5

**Logfiles**
[audiowagon_2021-09-05_16-26-50.zip](https://github.com/MoleMan1024/audiowagon_beta/files/7112154/audiowagon_2021-09-05_16-26-50.zip)

**Comment by lvitalis** [comment]
Related to #23

**Comment by MoleMan1024** [comment]
documentation on the new behaviour for tagging has been added to [FAQ section for 1.1.0](https://github.com/MoleMan1024/audiowagon/blob/master/CHANGELOG.md#110---2021-11-16)
