### ISSUE TITLE
App Freezes on "No Files Can Be Found" screen

### ISSUE THREAD

**Issue by jameswjd** [MoleMan1024/audiowagon#111]
Wife and I recently purchased a Volvo XC40. I had previously downloaded various types of music from my large collection onto several different USB sticks so they could be used in our Toyota Highlander. After buying a USB adapter for the new Volvo about a week ago and installing your AudioWagon App we were able to play the music on all four USB sticks. No problem at all. In fact, it worked great. We were thrilled. Unfortunately, I returned to the car from a shopping trip two days ago and no music would play via the USB already plugged into the system. It had been connected since I left the house earlier that morning and played music flawlessly. I had done absolutely nothing to it between that point and returning to the car after leaving the store. The screen seemed stuck on the "No Files Can Be Found" page. So, I removed the USB stick in place and tried another one. Same issue. After the "Dismiss" popup occurred it never then moved to the "Allow Access" Screen and the App automatically went back to the page showing "No Files Can Be Found." I then tried another one of my USB sticks, and the exact same thing occurred. At this point, I decided to Uninstall the App and Re-install it to see if this would fix the issue. Again, the "Dismiss" popup came on the screen, but the "Allow Access" popup did not. And, the very same problem happened again. No help. 

Yesterday, I turned on the car and my wife and I drove to the gym. The"Dismiss" popup came up and then the "Allow Access" popup occurred that had not the day before, and Voila! the App loaded all of the music on the installed USB and played with no problem at all. The only thing different between these two episodes is the elapse of about 26 hours. Nothing else.

I truly would appreciate your help. Without your App, there is no way to play all of our music in the Volvo that is contained on these USB sticks. And, it would certainly be nice to fix whatever is preventing it from operating in a consistent manner.

Thanks very much.

James

**Comment by jameswjd** [comment]
Wife and I recently purchased a Volvo XC40. I had previously downloaded various types of music from my large collection onto several different USB sticks so they could be used in our Toyota Highlander. After buying a USB adapter for the new Volvo about a week ago and installing your AudioWagon App we were able to play the music on all four USB sticks. No problem at all. In fact, it worked great. We were thrilled. Unfortunately, I returned to the car from a shopping trip two days ago and no music would play via the USB already plugged into the system. It had been connected since I left the house earlier that morning and played music flawlessly. I had done absolutely nothing to it between that point and returning to the car after leaving the store. The screen seemed stuck on the "No Files Can Be Found" page. So, I removed the USB stick in place and tried another one. Same issue. After the "Dismiss" popup occurred it never then moved to the "Allow Access" Screen and the App automatically went back to the page showing "No Files Can Be Found." I then tried another one of my USB sticks, and the exact same thing occurred. At this point, I decided to Uninstall the App and Re-install it to see if this would fix the issue. Again, the "Dismiss" popup came on the screen, but the "Allow Access" popup did not. And, the very same problem happened again. No help. 

Yesterday, I turned on the car and my wife and I drove to the gym. The"Dismiss" popup came up and then the "Allow Access" popup occurred that had not the day before, and Voila! the App loaded all of the music on the installed USB and played with no problem at all. The only thing different between these two episodes is the elapse of about 26 hours. Nothing else.

I truly would appreciate your help. Without your App, there is no way to play all of our music in the Volvo that is contained on these USB sticks. And, it would certainly be nice to fix whatever is preventing it from operating in a consistent manner.

Thanks very much.

James

**Comment by MoleMan1024** [comment]
@jameswjd : did you happen to have log file writing turned on in the settings while this happened? If yes, please provide that file to me (see [here](https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue) how to find it). If not, I can only make a guess of what happened.

**Comment by jameswjd** [comment]
Sorry, no. I don't even no what or where that is in the App.
James

    On Monday, February 27, 2023 at 07:38:53 AM PST, MoleMan1024 ***@***.***> wrote:  
 
 


@jameswjd : did you happen to have log file writing turned on in the settings while this happened? If yes, please provide that file to me (see here how to find it). If not, I can only make a guess of what happened.

**Comment by jameswjd** [comment]
I have now engaged the Log File.
Quick question. Are we supposed to use the "Eject" on your App every time we turn off the car? For example, I start the car and load a USB stick. I run several errands during the trip. Do I need to "Eject" every time I turn the car off at a stop along my route? My understanding from reading other comments was "No" that wasn't necessary. Is this correct?

Thanks.
James
    On Monday, February 27, 2023 at 07:41:38 AM PST, MoleMan1024 ***@***.***> wrote:  
 
 


Assigned #111 to @jameswjd.

**Comment by MoleMan1024** [comment]
@jameswjd : you don't need to use Eject when you turn off the car. You should only use it before you pull out the USB drive while Android is still running. Otherwise you can just leave it it plugged. When the car goes to sleep the app will stop using the USB drive, so this is safe.

If you don't have a log file from the issue, I can think of the following reason why this happened:

The Volvo USB component got stuck somewhere, that's why you did not see the popup that asked you for access to the USB drive. After leaving the car for a longer time Android will completely shut down which fixed it in this case. In case it happens again you can try to restart Android by doing an "infotainment reset" (by holding down the horizontal bar at bottom of screen for like a minute).

This was likely not something in my app and I could not fix it, it would need to be fixed by Volvo. But without log file, I can't say for sure.

I will close this ticket for now, you can re-open if you see the issue again.

**Comment by jameswjd** [comment]
Will do. Thanks.


    On Monday, February 27, 2023 at 11:18:01 AM PST, MoleMan1024 ***@***.***> wrote:  
 
 


@jameswjd : you don't need to use Eject when you turn off the car. You should only use it before you pull out the USB drive while Android is still running. Otherwise you can just leave it it plugged. When the car goes to sleep the app will stop using the USB drive, so this is safe.

If you don't have a log file from the issue, I can think of the following reason why this happened:

The Volvo USB component got stuck somewhere, that's why you did not see the popup that asked you for access to the USB drive. After leaving the car for a longer time Android will completely shut down which fixed it in this case. In case it happens again you can try to restart Android by doing an "infotainment reset" (by holding down the horizontal bar at bottom of screen for like a minute).

This was likely not something in my app and I could not fix it, it would need to be fixed by Volvo. But without log file, I can't say for sure.

I will close this ticket for now, you can re-open if you see the issue again.
