### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by ThoughtCriminal1** [MoleMan1024/audiowagon#117]
I realize this is a low-priority item, but I'd like to see a new, simpler icon that fits in better with automotive interfaces.  At least in myCadillac  Lyriq, the colorful icon really stands out from the rest. 

Anyway, just a thought. I realize you can't accommodate every different auto UI.  Keep up the great work!

![IMG_6778](https://user-images.githubusercontent.com/40638754/236570206-b9450c01-673a-432a-8f02-be1d02000d96.JPG)

**Comment by MoleMan1024** [comment]
Sorry, not happening.
