### ISSUE TITLE
Next and previous Track Option is not working 

### ISSUE THREAD

**Issue by TarikBe** [MoleMan1024/audiowagon#12]
Hello Moleman, 

when i play a Soundfile and i press Next or Previous Track (Touch/Steering Wheel) i get the message "There is no next Track" or "There is no previous Ttrack" ? 

I would be great if we can choose next/previous  and it plays the next available Track*

**Comment by MoleMan1024** [comment]
No further info received, closing. There is an improvement ticket #18 for this, I believe it is a usability issue.
