### ISSUE TITLE
When shuffle mode is enabled, selecting a track to play often results in a different track playing

### ISSUE THREAD

**Issue by bondms** [MoleMan1024/audiowagon#120]
**Describe the issue**
Selecting an audio file within a folder, whist shuffle mode is enabled, causes a track to start playing from that folder, but not necessarily the track selected.
If the user realises the cause of this confusion, a simple work-around is to first disable shuffle mode and then select the file to play.

**To Reproduce**
The issue can be easily reproduced.
Steps to reproduce the problematic behavior:
1. Enable shuffle mode.
2. Select an audio file in a folder containing multiple audio files.
The result is that a file from that folder starts playing, but usually it's not the selected one.

**Expected behavior**
I would expect the selected file to play first and followed by the other tracks in that folder in random order.
However, it would also be nice to also have a way of telling the application to play all the audio files in a particular folder in random order without having to specify a particular track to start with.

**AudioWagon version**
2.3.10

**Car version**
Polestar 2, P2.7.

**Logfiles**
I can provide log files if requested, but I believe the issue is easily reproducible following the steps above.

**Photos / Video**
I can provide photos or a video if requested, but I believe the issue is easily reproducible following the steps above.

**Comment by MoleMan1024** [comment]
Confirmed, same issue for tracks inside albums as well.

**Comment by MoleMan1024** [comment]
integrated in version 2.4.5

**Comment by bondms** [comment]
Working great now in 2.4.5.
Thanks for the quick fix!
