### ISSUE TITLE
Artist group boundaries incorrect

### ISSUE THREAD

**Issue by monkbroc** [MoleMan1024/audiowagon#122]
**Describe the issue**
I have more than 400 artist on my Samsung USB-C flash drive so AudioWagon splits them into 2 groups. The title of the start and end artist of the first group is correct, the title of the start artist of the second group is correct, but the title of the end artist of the second group is incorrect. It is an artist in the middle of the list.

**To Reproduce**
1. Add tracks by more than 400 artists on a USB drive
2. Start AudioWagon
3. Click on Artists
4. Click on each group, scroll to the bottom and expect the last artist to match the artist after the ... in the previous screen

**AudioWagon version**
2.4.6

**Car version**
2.9 for Volvo XC40 Recharge

**Logfiles**
[audiowagon_2023-07-02_17-23-08.log](https://github.com/MoleMan1024/audiowagon/files/11931516/audiowagon_2023-07-02_17-23-08.log)

**Photos / Video**

These photos show rising star ... Sugar Ray group. rising star is the first artist in the group when I click (sorry for the blurry photo) and Sugar Ray is somewhere in the middle. The last artist is Zz Top.
![20230702_173043](https://github.com/MoleMan1024/audiowagon/assets/1919681/66640a7c-7387-412f-9730-3d8a8082fc41)
![20230702_173105](https://github.com/MoleMan1024/audiowagon/assets/1919681/544a6c5d-2249-4f5a-97be-03ea5dbb209d)
![20230702_173121](https://github.com/MoleMan1024/audiowagon/assets/1919681/3df0b0e7-b19c-4f61-bd67-e2b14da9f3bb)
![20230702_173137](https://github.com/MoleMan1024/audiowagon/assets/1919681/57090256-fa2d-4803-84cc-3dc800a89b6e)

**Comment by MoleMan1024** [comment]
@monkbroc : Try the reset the internal database, it will recreate the groups afterwards:

1. with USB drive unplugged, go to AudioWagon settings and select "Delete databases"
2. checkmark the database that corresponds to your USB drive. If unsure which, just delete all. Click ok to delete them
3. Now re-read the metadata (depends on what you have set in "Read metadata". If "When USB drive connected", just plug in USB drive again. If "Manually", plug in USB drive and select "Read metadata now"). It will take a bit longer to read all metadata again now

This should solve the issue I think. If it still appears after this procedure, please let me know.

**Comment by MoleMan1024** [comment]
Confirmed the issue, will look into it. Thanks for the bug report.

**Comment by MoleMan1024** [comment]
fixed in v2.4.7

**Comment by monkbroc** [comment]
I confirm that 2.4.7 fixed this issue. Thanks!
