### ISSUE TITLE
Make default category configurable

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#124]
Received by e-mail:

As a car driver, 
I want to see the artist (files/albums) category as the default category to be opened when starting the app
so that I don't need to switch categories because I almost always use only that category.

This would require a setting to make the order of categories configurable.

**Comment by micksmothers** [comment]
I like your solution approach - configure the categories ordering as a configuration option and always default to the first one. Simple and should work on AAOS.

**Comment by MoleMan1024** [comment]
This will be in v2.5.1
