### ISSUE TITLE
Trying a new Samsung Flash Drive "No Supported Filesystem"

### ISSUE THREAD

**Issue by onetrev** [MoleMan1024/audiowagon#125]
**Describe the issue**
I just tried plugging in my new[ Samsung 64GB Flash Drive](https://www.jbhifi.com.au/products/samsung-type-c-usb-flash-drive-64gb-blue) and now I get this message: `USB: no supported filesystem`. It used to work fine with my old SanDisk Type-C flash drive. :(

**To Reproduce**
Steps to reproduce the problematic behavior:
1. Plus in the USB drive.
2. Load AudioWagon
3. Error message appears at the top of the app.

Also, in the AudioWagon settings it says: "Not compatible: Please formate USB using FAT32 filesystem". Which is frustrating since I did just format it with FAT32. Twice just for good meassure. 

**Expected behavior**
- I plug in the USB, it reads all the files and it's happy days!

**AudioWagon version**
2.4.7

**Car version**
Version 2.10 for XC40 (2023)

**Logfiles**
I'd love to provide a log file, but AudioWagon seemingly can't write to this device at all. Please let me know though if I can do anything to troubleshoot this. Hopefully it's not the same problem as [this issue.](https://github.com/MoleMan1024/audiowagon/issues/85) It sounds similar but the message is different so I have hope...

Note, these are the details Windows provides me for the device I'm trying to use:

```
Caption                     : Samsung Type-C USB Device
Description                 : Disk drive
InstallDate                 :
Name                        : Samsung Type-C USB Device
Status                      : OK
Availability                :
ConfigManagerErrorCode      : CM_PROB_NONE
ConfigManagerUserConfig     : False
CreationClassName           : Win32_PnPEntity
DeviceID                    : USBSTOR\DISK&VEN_SAMSUNG&PROD_TYPE-C&REV_1100\0373322040003947&0
ErrorCleared                :
ErrorDescription            :
LastErrorCode               :
PNPDeviceID                 : USBSTOR\DISK&VEN_SAMSUNG&PROD_TYPE-C&REV_1100\0373322040003947&0
PowerManagementCapabilities :
PowerManagementSupported    :
StatusInfo                  :
SystemCreationClassName     : Win32_ComputerSystem
SystemName                  : SurfacePro8Yo
ClassGuid                   : {4d36e967-e325-11ce-bfc1-08002be10318}
CompatibleID                : {USBSTOR\Disk, USBSTOR\RAW, GenDisk}
HardwareID                  : {USBSTOR\DiskSamsung_Type-C__________1100,
                              USBSTOR\DiskSamsung_Type-C__________, USBSTOR\DiskSamsung_,
                              USBSTOR\Samsung_Type-C__________1…}
Manufacturer                : (Standard disk drives)
PNPClass                    : DiskDrive
Present                     : True
Service                     : disk
PSComputerName              :
Class                       : DiskDrive
FriendlyName                : Samsung Type-C USB Device
InstanceId                  : USBSTOR\DISK&VEN_SAMSUNG&PROD_TYPE-C&REV_1100\0373322040003947&0
Problem                     : CM_PROB_NONE
ProblemDescription          :
```

**Comment by MoleMan1024** [comment]
@onetrev : what did you use to format the drive as FAT32? 
If you click on version in AudioWagon settings you can see the logfile in the car. You could take a photo of that and post it here after pluggin in the drive.

**Comment by onetrev** [comment]
Thanks for the quick follow up! Facepalm for me🤦. I was in a hurry and just used Windows Explorer. And I forgot about the 32GB limit so it was formatted as `exFAT`. Usually that works for most things but apparently AAOS is picky.

So good news after _actually_ formatting it was FAT32 the device is recognised and all is good🎉. 

Except... I did notice an odd new tiny issue. I can no longer `Delete Databases` now with this device. When I select that option it opens up with no database to select so hitting the Okay / Yes button does nothing. Before I changed USB devices there used to be a **db** with a date and such you could select. So for now the only way for delete the database is to uninstall AudioWagon. 

I can create a new issue for this if you want, or we can just leave it as it's very minor? Cheers!

**Comment by MoleMan1024** [comment]
> Except... I did notice an odd new tiny issue. I can no longer `Delete Databases` now with this device. When I select that option it opens up with no database to select so hitting the Okay / Yes button does nothing. Before I changed USB devices there used to be a **db** with a date and such you could select. 

Did you make sure to eject the USB device before trying that? A database that is currently in-use can not be deleted.

**Comment by onetrev** [comment]
Ugh. Whoops. No. Makes total sense I should know better being a web dev. Double facepalm. 🤦 Or to misquote a great line from Star Trek 4, "double dumbass on me".  Thank you! And I'll be making two 'good cause' donations now. :)
