### ISSUE TITLE
File system only search does not work anymore

### ISSUE THREAD

**Issue by agdejager** [MoleMan1024/audiowagon#126]
**Describe the issue**
File system only search does not work anymore only Files only USB Stick.
Used to work before some updates.

**To Reproduce**

Steps to reproduce the problematic behavior:
1. Go to search (amplyfying glas)
2. Type something to search for like "Adele"
3. See error: "No such medium"

**Expected behavior**
I normally expect results for "Adele"

**AudioWagon version**
2.4.7

**Car version**
2.10

**Logfiles**
None

**Photos / Video**
none

**Comment by MoleMan1024** [comment]
@agdejager : please provide a logfile

**Comment by agdejager** [comment]
[audiowagon_2023-07-31_16-16-07.log](https://github.com/MoleMan1024/audiowagon/files/12216052/audiowagon_2023-07-31_16-16-07.log)

The logfile you asked for. :-)

**Comment by MoleMan1024** [comment]
@agdejager : the log file shows that you have not yet indexed any metadata:

`2023-07-31 16:15:50.055 [DEBUG   ][23554-29191][CHRootTracks            ] Showing pseudo MediaItem 'No entries available': Metadata noch nicht ausgelesen'`

This is required for searching. You have the choice to index everything when USB drive plugged in, index manually by hand or index file paths only (see [FAQ](https://moleman1024.github.io/audiowagon/faq.html#what-happens-during-indexing)). Please enable at least the mode "Read metadata: file paths only", then search should work again.

**Comment by MoleMan1024** [comment]
No worries
