### ISSUE TITLE
GUI no longer reacts after using for some time in Renault cars

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#127]
**Describe the issue**
By accident I came across this [forum post](https://www.megane-e-forum.de/forum/thread/1005-open-r-link-display-wird-bleibt-schwarz-nach-installation-von-android-apps/). It describes a problem that the main screen except the climate bar goes glack when using AudioWagon with many files for some time. Since this only happens in Renaults it is likely a problem specific to their AAOS build. I do not have this car but have seen something similar sometimes where cover art disappears on the default AAOS 10 build I use for testing on my phone. Volvo/Polestar users have never reported anything like this. If I try to fix the the cover art disappearing, maybe that fixes this one for Renault drivers as well.

As a reminder to everyone: if you do not report an issue, do not assume I know about it, I only found this accidentally! If I don't know about an issue, I can never try to fix it.

Also please read the FAQ/manual, some other "faults" reported in that forum post are not actually faults or have a solution already.

**Comment by MoleMan1024** [comment]
This should be fixed in v2.5.2

**Comment by stbi28** [comment]
Hello I have a Renault, and the tablet problem frozen on 06/14/23. I attach the logs. Hope this is useful to you. THANKS
[audiowagon_2023-06-14_14-18-29.log](https://github.com/MoleMan1024/audiowagon/files/12361948/audiowagon_2023-06-14_14-18-29.log)
[audiowagon_2023-06-14_14-41-44.log](https://github.com/MoleMan1024/audiowagon/files/12361950/audiowagon_2023-06-14_14-41-44.log)
[audiowagon_2023-06-14_16-11-20.log](https://github.com/MoleMan1024/audiowagon/files/12361951/audiowagon_2023-06-14_16-11-20.log)
[audiowagon_2023-06-14_16-40-35.log](https://github.com/MoleMan1024/audiowagon/files/12361952/audiowagon_2023-06-14_16-40-35.log)
[audiowagon_2023-06-14_16-42-47.log](https://github.com/MoleMan1024/audiowagon/files/12361953/audiowagon_2023-06-14_16-42-47.log)
[audiowagon_2023-06-14_16-45-10.log](https://github.com/MoleMan1024/audiowagon/files/12361954/audiowagon_2023-06-14_16-45-10.log)
[audiowagon_2023-06-14_17-20-30.log](https://github.com/MoleMan1024/audiowagon/files/12361955/audiowagon_2023-06-14_17-20-30.log)
[audiowagon_2023-06-14_17-25-14.log](https://github.com/MoleMan1024/audiowagon/files/12361956/audiowagon_2023-06-14_17-25-14.log)
[audiowagon_2023-06-14_17-27-54.log](https://github.com/MoleMan1024/audiowagon/files/12361957/audiowagon_2023-06-14_17-27-54.log)
[audiowagon_2023-06-14_17-34-00.log](https://github.com/MoleMan1024/audiowagon/files/12361958/audiowagon_2023-06-14_17-34-00.log)
[audiowagon_2023-06-14_17-38-04.log](https://github.com/MoleMan1024/audiowagon/files/12361959/audiowagon_2023-06-14_17-38-04.log)
[audiowagon_2023-06-14_17-47-04.log](https://github.com/MoleMan1024/audiowagon/files/12361961/audiowagon_2023-06-14_17-47-04.log)
[audiowagon_2023-06-14_17-48-24.log](https://github.com/MoleMan1024/audiowagon/files/12361962/audiowagon_2023-06-14_17-48-24.log)
[audiowagon_2023-06-15_09-24-08.log](https://github.com/MoleMan1024/audiowagon/files/12361963/audiowagon_2023-06-15_09-24-08.log)
[audiowagon_2023-06-15_09-25-37.log](https://github.com/MoleMan1024/audiowagon/files/12361964/audiowagon_2023-06-15_09-25-37.log)
[audiowagon_2023-06-15_09-27-37.log](https://github.com/MoleMan1024/audiowagon/files/12361965/audiowagon_2023-06-15_09-27-37.log)
