### ISSUE TITLE
Persistent "USB device error"

### ISSUE THREAD

**Issue by gbrickell** [MoleMan1024/audiowagon#128]
**Describe the issue**
I'm getting a persistent "USB device error" whenever the car is started and this happens with every USB flash drive that I have tried ie several older USBs using an adaptor as well as a newly bought USB Type C drive. Once I dismiss the error the application is happy ie it finds all the files and plays everything and the system menu 'says' the USB is OK. This happens literally every time I start the car so I have to go through the 'Dismiss' and the 'OK' screens every time I go anywhere. Is there something else I should do or is this some sort of bug? The car was only delivered new on 15 Aug'23 and it has happened all the time and is always reproducible.

**AudioWagon version**
The application is version 2.5.2 only just installed so I assume it is the latest.

**Car version**
The car is a Polestar 2 with the latest software ie P2.10 -  Android 11 with the latest security patch level 1 March 2023

**Logfiles**
Even though logfiles were enabled there wasn't any to be found on the USB drive??

**Photos / Video**
Two screen shots attached
![PXL_20230821_092159125_800w](https://github.com/MoleMan1024/audiowagon/assets/39712542/3767424e-a339-4a96-949b-85c1889c442f)
![PXL_20230821_092747885 MP_800w](https://github.com/MoleMan1024/audiowagon/assets/39712542/c7e0bc60-9f35-42ee-9d62-6ca8fa0f5577)

**Comment by MoleMan1024** [comment]
Same as https://github.com/MoleMan1024/audiowagon/issues/73 

Please read the [Frequently Asked Questions](https://moleman1024.github.io/audiowagon/faq.html#why-is-there-a-popup-about-usb-device-is-not-supported-when-the-usb-device-works-fine)
