### ISSUE TITLE
Keep currently playing item centered in playlist page

### ISSUE THREAD

**Issue by damokles66** [MoleMan1024/audiowagon#132]
While being in the playlist view, the current item is highligted and when the next track begins the view remains constant, until we reach the end of the page, where we then scroll down one line.
This is ok, but I think it could be improved by keeping the currently played item centered(if possible). This would allow us to easier see upcoming items and skip if we want to, without having to manually scroll down (while driving).

Essentially the request is as following, when playing the next item:
Keep current behaviour until we reach the center of a page
If the remaining playlist is longer than the remaining "half-page" = we have a lot to play -> keep the current item centered, shifting the entire table one row
Once the remaining playlist is less than a "half page" revert to current behaviour, iterating over them until we hit the last item in the bottom row.

Best regards,
Sebastian

**Comment by MoleMan1024** [comment]
This was asked before. I have no influence on the browse view GUI. You need to request such a feature at Google or Polestar/Volvo.
