### ISSUE TITLE
USB drive not recognized

### ISSUE THREAD

**Issue by petard** [MoleMan1024/audiowagon#134]
**Describe the issue**
AudioWagon does not recognise the SSD drive (Samsung EVO in external USB enclosure) connected to my AAOS Volvo. The drive has 1TB (with 129GB used) with a single partition formatted with FAT32 filesystem. A 128GB SanDisk thumb drive works fine.

**To Reproduce**
1. Connect above SSD drive to the white bordered USB port in the car
2. Open AudioWagon
3. Message appears "Reading files"
4. Error appears after 10-20 seconds "File system not recognised"
5. The SSD has a "LOST.DIR" folder on it which is empty after connecting with AudioWagon

**Expected behavior**
AudioWagon starts indexing the files on the disc

**AudioWagon version**
2.5.9

**Car version**
Volvo V90, AAOS version 2.13.2 
****

**Comment by MoleMan1024** [comment]
@petard : please provide a log file

**Comment by MoleMan1024** [comment]
@petard : since the filesystem is not recognized you can't provide any log files from the filesystem. Please go to AudioWagon settings and tap on version, it will show the log on screen. Take a few photos of scrollable log and attach them here please, I should be able to see why the filesystem is not recognized.

**Comment by petard** [comment]
The disk was formatted using diskutil on a Mac, taking another look I noticed there was an EFI partition left. Diskutil leaves this partition untouched even when repartitioning the drive.

After reformatting the disk to remove the EFI using `diskutil eraseDisk FAT32 MYDISC MBR <logicaladdress>` in Terminal the drive was recognised by AudioWagon and the files were indexed.

Closing for now.
