### ISSUE TITLE
Indexed files not visible in Files tab

### ISSUE THREAD

**Issue by petard** [MoleMan1024/audiowagon#135]
**Describe the issue**
After indexing about 18,000 files only a few tracks / artists / files are shown in the tabs. However, it seems all files have been indexed as they can be accessed and played using search or by playing all tracks randomly. I have started indexing manually from Settings. In the FAQ it mentions grouping occurs with more than 500 files / objects but this issue seems different as no grouping happens.

**To Reproduce**
1. Index collection of 18,000 files
2. Click Files tab
3. Select folder on disk containing all the music data
4. Only four files are shown in the folder

**Expected behavior**
1. Index collection of 18,000 files
2. Click Files tab
3. Select folder on disk containing all the music data
4. 1.182 sub-folder are shown for access 

**AudioWagon version**
2.5.9

**Car version**
AAOS version 2.13.2

**Photos / Video**
1.  Files tab, root folder on disk:
![IMG_0806](https://github.com/MoleMan1024/audiowagon/assets/947001/45205c07-bcd7-4aa0-9b39-c9b56f73a803)
2. Listing of "Music" folder. This folder has 1,257 subfolder on disk but only three are visible in the app.
![IMG_0807](https://github.com/MoleMan1024/audiowagon/assets/947001/011763b1-61d9-4699-9f71-20ed3a085037)
3. For comparison search for "met" to show all files seem to be indexed and in the database
![IMG_0808](https://github.com/MoleMan1024/audiowagon/assets/947001/2a3e0a2a-27de-4676-a9b4-54806ddc7300)

**Comment by MoleMan1024** [comment]
@petard : This is the grouping. It has 400 directories in each of those 3 "blocks". And each directory might be grouped again if it contains more than 400 files in it.

**Comment by petard** [comment]
Thanks for information. In the FAQ the grouping icons look different, that's why I though it is something else.

Please keep up the good work and thank you for your outstanding support.
