### ISSUE TITLE
Can't start Audiowagon with the car in motion

### ISSUE THREAD

**Issue by Skywagon182** [MoleMan1024/audiowagon#144]
**Describe the issue**
Since Volvo launched v3.0.3 the message "Allow Audiowagon to acess XXXX?" is hidden when the vehicle is in motion (same as the settings menu, which I understand for safety reasons).
Due to this, to start Audiowagon now (since v3.0.3) you have to stop so that the message pops up and can be answered.

**To Reproduce**
Try to switch to Audiowagon from any other source while driving

**Expected behavior**
As it was working before. The message poped up and could be answered while driving

**AudioWagon version**
2.6.10

**Car version**
Volvo Android Auto v3.0.3

**Logfiles**
na

**Photos / Video**
not necessary

**Comment by MoleMan1024** [comment]
Please check here: https://github.com/MoleMan1024/audiowagon/issues/142
