### ISSUE TITLE
Full width of screen is not taken into account when ellipsizing entries in browse view

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#148]
received via e-mail from a user in a Renault Austral: 
![20240702_193011](https://github.com/MoleMan1024/audiowagon/assets/70017071/650e8fdb-1ca8-4ff9-8488-a2fd3107e686)

**Comment by MoleMan1024** [comment]
I checked my code and I only ellipsize (i.e. add "…" to browse view entries) when there are groups shown. In the screenshot above there are no groups shown. That means the issue is on the GUI side which is under control of Renault. Please raise ticket to them.

This is what a long title looks like in Polestar 2 emulator (also Android 10):
![image](https://github.com/MoleMan1024/audiowagon/assets/70017071/217af46d-a7fd-4e9f-a3e6-d5457f7bb92b)

**Comment by mekp-code** [comment]
see in the attached photo the pathname can contain at least 28 characters
my car is renault autral with open r link

![Image](https://github.com/user-attachments/assets/6557e8a5-c874-4a17-b295-dc1eccaf9c25)
