### ISSUE TITLE
Album art not always shown.

### ISSUE THREAD

**Issue by JazzySOB** [MoleMan1024/audiowagon#149]
**Describe the issue**
Some songs do not show album art. When I play an album, the MP3s of which are all tagged in the same way (with Mp3tag) I see the album art on the screen, but randomly for some songs you only see a music note icon. I make compilations myself and tag the MP3 files all in the same way and yet I don't see album art for some songs. With other devices such as a media player as Winamp and Foobar 2000 and also on my telephone I see album art on all the songs, so it seems to be an AudioWagon issue.

**Expected behavior**
<Describe what you expected to happen>
Album art on all songs.

**AudioWagon version**
This problem occurs with all previous versions, now using latest version, 2.6.1.1.

**Car version**
<Which software version are you running in your car? (e.g. P2127 for Polestar 2)>
v3.0.3. for Volvo XC40

**Comment by MoleMan1024** [comment]
@JazzySOB : please provide a log file https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue

**Comment by JazzySOB** [comment]
Hi MoleMan,
Thanks for the quick reply!
I have removed all log files from the USM stick and inserted it back in to the car for a fresh start.
The first songs didn's show album art, but after selecting a new folder with music, it seems I can't reproduce the issue anymore.
I have added the log file anyway.
Thanks for helping out, I enjoy AudioWagon every day!
[audiowagon_2024-07-06_13-31-16.log](https://github.com/user-attachments/files/16115851/audiowagon_2024-07-06_13-31-16.log)

**Comment by MoleMan1024** [comment]
@JazzySOB : ok, glad to hear. I will close this ticket then. If the issue appears again, first try the usual troubleshooting steps ( e.g. reboot infotainment system ). If the issue still appears, put a comment here or open a new ticket.

**Comment by JazzySOB** [comment]
Unfortunately, the issue has been returned. When I start driving and playing some songs, the album art was missing again and replaced with the music note icon.
I have added the last two log files.
[audiowagon_2024-07-06_20-01-03.log](https://github.com/user-attachments/files/16116990/audiowagon_2024-07-06_20-01-03.log)
[audiowagon_2024-07-06_20-05-47.log](https://github.com/user-attachments/files/16116991/audiowagon_2024-07-06_20-05-47.log)
