### ISSUE TITLE
Playback not resuming (in Polestar 2 >=P2127) when re-entering the car

### ISSUE THREAD

**Issue by lvitalis** [MoleMan1024/audiowagon#15]
**Describe the issue**
We re-entering the car after some time, playback does not resume as it should.

**To Reproduce**
- Enter the car
- Accept the USB permission
- Start a track
- Exit and lock the car
- Wait at least 20 seconds
- Unlock and re-enter the car
- Accept the USB permission
- Music does not resume

`Please note that if you unlock and re-enter the car quickly (but slow enough that music stops and screen turns off), the USB permission is not requested, the playback resumes.`

**Expected behavior**
Last track should resume where it was paused.

**AudioWagon version**
0.25

**Logfiles**
Log of two successful resumes
[Two successful resumes.log](https://github.com/MoleMan1024/audiowagon_beta/files/7178866/Two.successful.resumes.log)

Log of a failed resume
[One failed resume.log](https://github.com/MoleMan1024/audiowagon_beta/files/7178865/One.failed.resume.log)

**Comment by MoleMan1024** [comment]
I got the OTA update recently, can test this myself in the car now.

**Comment by MoleMan1024** [comment]
After trying a couple of times I don't think my fix works yet. I have the impression the app is not shut down when exiting the car but it is suspended to RAM it seems.

**Comment by MoleMan1024** [comment]
New fix prepared for next version.

**Comment by MoleMan1024** [comment]
@lvitalis : it was partially fixed in v0.3.4. I found another situation where it did not work which I improved as well. I have the new version in my car as well now so I can test it myself.

**Comment by MoleMan1024** [comment]
This should now be fully working in v0.4.0.
