### ISSUE TITLE
Album art missing from some songs

### ISSUE THREAD

**Issue by JazzySOB** [MoleMan1024/audiowagon#150]
**Describe the issue**
Unfortunately, the issue with the missing album art has been returned. When I start driving and playing some songs, the album art was missing again and replaced with the music note icon.
I have added the last two log files.

**Expected behavior**
Album art on all songs.

**AudioWagon version**
2.6.11

**Car version**
3.0.3. for Volvo XC40

**Logfiles**
[audiowagon_2024-07-06_20-01-03.log](https://github.com/user-attachments/files/16117003/audiowagon_2024-07-06_20-01-03.log)
[audiowagon_2024-07-06_20-05-47.log](https://github.com/user-attachments/files/16117004/audiowagon_2024-07-06_20-05-47.log)

**Comment by MoleMan1024** [comment]
@JazzySOB : please provide more info
- "when I started driving" -> I can not see that in the log files, please provide exact date and time when the problem appeared aligned with the log files
- "playing some songs" -> which songs exactly did you play when?
- which songs/tracks were missing album art?
- did you already try the infotainment reboot [as I recommended before?](https://github.com/MoleMan1024/audiowagon/issues/149). If not, please do that first, often when album art does not show properly, it is an Android media center issue

**Comment by MoleMan1024** [comment]
@JazzySOB : I don't agree that you need to live with the album art problem. Maybe just keep the log file writing turned on and next time you observe the issue provide me all the logs. There must be a reason for it, I just need to more information to understand how and when it can happen to be able to investigate it.

**Comment by MoleMan1024** [comment]
No further log files provided after a month, closing ticket.
