### ISSUE TITLE
Audiowagon usb access

### ISSUE THREAD

**Issue by WimvanDijk** [MoleMan1024/audiowagon#155]
Audiowagon can not access to usb when driving, only when car is not moving. Before the car update is wasxworking well, you only must give access after every car start. But this popup comes not when driving. Not allowed when driving, 

 Wim van dijk, volvo 2022 xc60

**Comment by MoleMan1024** [comment]
Duplicate of https://github.com/MoleMan1024/audiowagon/issues/142
