### ISSUE TITLE
Tracks selected in tracks view shall not play a random track selection but instead play tracks in order.

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#157]
Please describe the feature you would like to see, for example in the form of a user story:

As a person with autism,
I want the app to react in a predictable manner always
so that I am not stressed out.

When selecting a random track from tracks view, a random playback queue of tracks is created. This causes issues for autistic people. Tracks shall play in alphabetical order instead, like they are shown in the tracks view.
The random playback queue for tracks can still be achieved via either the "shuffle all" button or using the shuffle mode.

**Comment by MoleMan1024** [comment]
Will be changed in v2.8.0

**Comment by nramsbottom** [comment]
I really dislike this change and think it draws the drivers attention away to correct. If I have searched for a specific track, I expect the app to continue with the shuffled playlist. To reshuffle the playlist from the search requires three touches to the screen, touches that take focus away from the road.

This behaviour should be opt-in.

**Comment by MoleMan1024** [comment]
@nramsbottom : when you use the search function to select a specific track or when you select a track from the list in "Tracks" view you would never continue a playback queue you were playing before, such a feature was never in the app. The app would always create a new random playback queue of tracks. 
If you always want the playback queue shuffled after selecting a track, then first create a playback queue, turn on shuffle mode using the 3 dots extra menue and leave it on. Next time you pick a new track, the app will create a new playback queue that is also shuffled starting with the track you picked.

Maybe I don't get what you mean.
