### ISSUE TITLE
Support for Dolby Atmos encoded FLAC

### ISSUE THREAD

**Issue by calebu2** [MoleMan1024/audiowagon#158]
As a Polestar 2 owner with eyes on the Polestar 3 (which supports Dolby Atmos) I would like to be able to play AC3 encoded files on the app. Apps like VLC have support for AC3 but when I load the file in Audiowagon it gives an error. Other encodings work fine. I can try to re-download the 2-channel versions of albums but I have a bunch of them in AC3/Atmos format and managing the different versions of albums between vehicles would be a pain.

**Comment by MoleMan1024** [comment]
I will only support what the Android system supports natively, I will not add custom decoders, it is too much work, sorry.

**Comment by MoleMan1024** [comment]
If they support Dolby Atmos in Polestar 3 you could argue they need to provide an appropriate audio player also in order to use that, otherwise all these speakers are pointless.

**Comment by MoleMan1024** [comment]
Based on https://professionalsupport.dolby.com/s/article/Support-Dolby-Atmos-in-Android-Automotive-OS-media-apps?language=en_US it looks like this would need to be implemented by Android media player/Exoplayer which is part of AAOS, not by a media service like AudioWagon. So it might work automatically if done in Polestar 3. But it will never work in a car that does not support Dolby Atmos natively.
