### ISSUE TITLE
App hangs on "please wait" after start

### ISSUE THREAD

**Issue by petard** [MoleMan1024/audiowagon#160]
**Describe the issue**
I noted over the last 2-3 weeks that Audiowagon hangs after starting the car with the USB disk already attached to the USB port. Haven't changed the USB content or AAOS version for months so assuming it might be related to Audiowagon.

**To Reproduce**
1. Start car with USB drive connected to USB port.
2. Accept permission screen
3. Audiowagen shows "Please wait" screen
4. Nothing happens after waiting 2-3 minutes.
5. Disconnect USB drive and reconnect
6. Audiowagon shows "Please Wait" but then quickly (< 1 minute) starts playback

**Expected behavior**
Audiowagon starts playing quickly after accepting permission screen

**AudioWagon version**
2.8.

**Car version**
Volvo AAOS 3.1.9

**Logfiles**
Will add.

**Comment by MoleMan1024** [comment]
will check it when I get log files

**Comment by MoleMan1024** [comment]
no logs received, closing
