### ISSUE TITLE
Better Compilation Support (FLAC)

### ISSUE THREAD

**Issue by lvitalis** [MoleMan1024/audiowagon#22]
As a music lover and obsessive audio library tagger,
I want AudioWagon to handle compilations, 
so that I can browse my catalog easily.

**Use case**
A famous artist, John, has released a compilation album of 20 tracks, all covers or remixes of his own songs.
Each track was made by a different artist, of various notoriety.

The tracks are tagged like this :
- `ARTIST` contains the name of the artist who did the song cover (individual artist for each track)
- `ALBUM ARTIST` contains John
- `ALBUM` contains Covers of John

**Result (in v0.3.4)**
Albums list contains the same album, repeated for each different `ARTIST` tag .
If you click on an album, you only get the songs from `ARTIST`.
Artists list contains  20 somewhat unknown artists.
Artists list does not containt the main artist, John. 

**Expected result**
Albums list should contain the album once with the `ALBUM ARTIST` name.
An album should include every track of the same `ALBUM` and `ALBUM ARTIST`.
Artists list should only contain `ALBUM ARTIST`.
Artists list should not contain every individual `ARTIST` name.

When playing, the track's `ARTIST` tag can still be displayed on the screen.
Decision to include `ALBUM ARTIST` is up to you.

**Further improvement**
User could decide in the settings to include the individual artists of a compilation in the Artists list.

[FLAC-compilation.zip](https://github.com/MoleMan1024/audiowagon/files/7198242/FLAC-compilation.zip)

NB : A standard was not established early on and, sadly, both `ALBUM ARTIST` and `ALBUMARTIST` tags are used by different tagging softwares. Therefore, it would be necessary to read them both, if the feature is implemented.

NB2 : In MP3 files, Album Artist is stored in the `TPE2` tag.

**Comment by lvitalis** [comment]
Made my description much more detailed.

**Comment by MoleMan1024** [comment]
this has been added in 1.1.0, see https://github.com/MoleMan1024/audiowagon/blob/master/CHANGELOG.md#110---2021-11-16
