### ISSUE TITLE
Audio mute during navigation

### ISSUE THREAD

**Issue by nikagersonlohman** [MoleMan1024/audiowagon#24]
I want the music to _not_ pause temporarily when the navigation system announces the next turn, but continue with less volume, like other audio applications

**Comment by MoleMan1024** [comment]
I actually tried this but there is still a small pause for the audio when the route guidance announcement comes in. That is why I decided to pause the music instead.

**Comment by nikagersonlohman** [comment]
No worries, just wanted to make sure it was tracked in here 👍

**Comment by nikagersonlohman** [comment]
If I'd be developing an app I would try to align it to other apps. As far as I know it's lower volume for any other app; they never pause/mute entirely?

**Comment by MoleMan1024** [comment]
In version 1.2.0 a setting was implemented to select to either lower the volume of the music or pause it. I have not observed the short pause in the music when lowering volume when I tested this now.
