### ISSUE TITLE
USB message always popped up

### ISSUE THREAD

**Issue by nikagersonlohman** [MoleMan1024/audiowagon#25]
On my Volvo XC40 P8 the message to allow USB for audio wagon is always (when starting the car / opening the app) popped up (also when checking the checkmark)... looks like an AAOS issue for the XC40 P8 as the "Downloaded" section is not available in settings as mentioned in the message

**Comment by MoleMan1024** [comment]
hi, please read
https://moleman1024.github.io/audiowagon/#why-does-the-permission-popup-appear-each-time-the-always-open-audiowagon--checkbox-does-not-do-anything
I cannot solve this

**Comment by nikagersonlohman** [comment]
No worries, just wanted to make sure it was tracked in here 👍
