### ISSUE TITLE
Albums/artists do not load in certain cases

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#29]
received from beta tester:

I have now restructured but it is still not working as i expected.
The structure is now as follows. I use 2 USB-sticks with different labels.
the 1st one with the
`Music/Artist/<known albums>/<title>.mp3`
structure is working pretty fine.
The 2nd one with the
`/YouTube/Artist/<mostly unknown album mostly artist name>/<Title>.mp3`
is not working fine.
The only possibility to play songs is over the numbers list.
**The others, Artist and Albums are telling me loading but for me that takes too long and is never ending.**

What did you expect to happen?
Same behaviour as for <known albums>

At what date/time did the issue happen? (so I can align with the timestamps in the log files)
It happens all the time

Which version of AudioWagon were you using? (see Settings)
0.3.4

Which version is your car’s software? (e.g. P2124 on a Polestar2)
P2135

Log files are being created continously on your USB drive (if this is enabled in the settings). Please attach these logfiles from around the date/time when this happened (also provide previous logfile). They have filenames like aw_logs_<num>/audiowagon_<date_and_time>.log.
log file attached.

[issue_youtube.zip](https://github.com/MoleMan1024/audiowagon/files/7231191/issue_youtube.zip)

**Comment by MoleMan1024** [comment]
The issue is that these files do not seem to contain metadata, so they are assigned the unknown artist ID -1

```
2021-09-26 09:46:21.070 [DEBUG   ][22062][AudioItemRepo       ] Artist -1 has 3499 tracks without album info
2021-09-26 09:46:21.073 [DEBUG   ][22062][AudioItemRepo       ] Returning 1 albums for artist -1
```

Requesting 3500 items in onLoadChildren() will either take very long time or will not work at all due to BINDER transaction failure because of the size. I need a better way to handle libraries with lots of untagged artists/albums.

**Comment by MoleMan1024** [comment]
I have prepared track groups for this case as well which should solve this issue.

**Comment by agdejager** [comment]
@MoleMan1024 
above is stated : 
the 1st one with the
Music/Artist//<title>.mp3
structure is working pretty fine.
The 2nd one with the
/YouTube/Artist//<Title>.mp3

There is something dropped out of the text :
Music/Artist/**_Album_**/<title>.mp3
and
/YouTube/Artist/**_PseudoAlbum_**/<Title>.mp3

**Comment by MoleMan1024** [comment]
@agdejager : I fixed the description now

**Comment by MoleMan1024** [comment]
This has been improved for v0.4.0.
