### ISSUE TITLE
Starting position when using file/directory browsing.

### ISSUE THREAD

**Issue by agdejager** [MoleMan1024/audiowagon#39]
Please describe the feature you would like to see, for example in the form of a user story:

As a car driver
I want after restart of the app when using file/directory browsing that the file/directory browsing starts at the last position
before the restart. 
so that i do not have to start from the very beginning all the time.

**Comment by MoleMan1024** [comment]
I am sorry but I have no control over this behaviour, this is decided by the media browser client, I only implement the media browser service.
