### ISSUE TITLE
Version 0.6.1 : Options selections immediately aborts the app.

### ISSUE THREAD

**Issue by agdejager** [MoleMan1024/audiowagon#40]
**Describe the issue**
Select the options button and the app aborts immediately.

**To Reproduce**
Evertime you select the options menu button.
**Expected behavior**
See the options menu.

**AudioWagon version**
0.6.1 (the last at 02.11.2021)

**Car version**
P1.7

**Logfiles**
none
**Photos / Video**
none

**Comment by MoleMan1024** [comment]
same as #41
