### ISSUE TITLE
allow voice action to play with a slot

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#43]
As a car driver,
I want to use voice commands to select a certain artist/album/track by voice,
so that I don't need to take my eyes off the road.

**Comment by MoleMan1024** [comment]
It looks like I found a way to make this work... these intents are important: [https://source.android.com/devices/automotive/radio#play-intents](https://source.android.com/devices/automotive/radio#play-intents)

**Comment by lvitalis** [comment]
If you have not already read this, it might be interesting 

https://source.android.com/devices/automotive/voice/voice_interaction_guide/fulfilling_commands

**Comment by MoleMan1024** [comment]
this should work now in v1.0.1
