### ISSUE TITLE
Back to Start of Song Option

### ISSUE THREAD

**Issue by DaRealHibachi** [MoleMan1024/audiowagon#45]
Please describe the feature you would like to see, for example in the form of a user story:

Hi,

Is it possible to implement the following option?

When playing a song and pressing the *back* key, whether on screen or via the button on the steering wheel, it plays the previous song. 

Is it possible to have the option that the *back* key "skips" to the start of the current song first, and then (after another *back* press) to the previous song after? At the moment if you want to listen to the current song again, you first have to skip to the previous song and then skip forward again.

Thanks in advance!

**Comment by MoleMan1024** [comment]
released in version 1.3.0
