### ISSUE TITLE
File system view recursive playback

### ISSUE THREAD

**Issue by micksmothers** [MoleMan1024/audiowagon#50]
This is for a filesystem organization on the USB drive of nested directories:

As a car driver, 
I want to play/shuffle all files recursively from a selected directory on the filesystem 
so that I can take advantage of the organization of music files by folder I have on the USB drive

Hope this makes sense.

**Comment by MoleMan1024** [comment]
@micksmothers : yes I understood it, thanks for the request, this has been requested before as well.

**Comment by MoleMan1024** [comment]
Will be in version 2.0.0
