### ISSUE TITLE
Album Arts

### ISSUE THREAD

**Issue by p-a-tellnes** [MoleMan1024/audiowagon#52]
Hi, I’m @p-a-tellnes
Is there any chance of showing the album art if this in form of a .jpg is stored together with the tracks of an album in a folder?
(One folder for each album).

I got my PS2 two weeks ago and immediately discovered the need for Audiowagon as I saw this in the PS2 forum.
I bought a suitable memory stick and the app works perfectly, but it would be nice to show the album graphics instead of just the note symbol.

**Comment by MoleMan1024** [comment]
this has already been requested in issue #36
