### ISSUE TITLE
display albums as tiles instead of as a list

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#57]
As a car driver, 
I want to be able to tap on an album easily while driving (i.e. I prefer bigger album tiles instead of list rows)
so that I am not distracted from the road.

**Comment by bluecar112** [comment]
Great idea as I know most of my collection by album cover.  Applying same support for folder art as in 1.3.0 would be great!

**Comment by MoleMan1024** [comment]
Will be in version 2.0.0
