### ISSUE TITLE
Cant Install on Polestar

### ISSUE THREAD

**Issue by gdotp01** [MoleMan1024/audiowagon#59]
Im sure thius is probably a Polestar/google issue but I can't seem to install this application at all and was wondering if someone could point me in the right direction. It appears to be installed according to google but its not appearing in the car. I recently installed Amazon Music and that went on fine.  When i go into google it looks like there are two 'polestar devices' set up and i've tried both of these. 
![IMG_5311](https://user-images.githubusercontent.com/50060482/148055799-0d78fc9a-d1b7-4753-b61f-a1973265088e.PNG)
![IMG_5310](https://user-images.githubusercontent.com/50060482/148055813-933079f6-233d-48ab-8305-3eac8f31bf12.PNG)

**Comment by gdotp01** [comment]
Just adding to this. I just installed audio crate and this went on just fine.

**Comment by MoleMan1024** [comment]
@gdotp01 : did you try to find the app in the play store in the car?

**Comment by gdotp01** [comment]
In the play store. Should I try from the car? 
There are two profiles set up for my wife and myself but under different google logins. I’ve no idea why there are two polestars either as devices. The dates suggest it’s when I first set it up and then again when r1.8 broke my PAK and I was asked by PS support to set it all up again.

**Comment by MoleMan1024** [comment]
@gdotp01 : yes please try installing via the Play Store in the car's interface

**Comment by gdotp01** [comment]
Ive managed to install it. Not sure how but it seemed to appear after a day or so of trying. can't get it to recognise the USB stick now but that's another story.

**Comment by MoleMan1024** [comment]
@gdotp01 : Okay. See [this FAQ section regarding why USB drive might not work](https://moleman1024.github.io/audiowagon/faq.html#why-is-my-usb-drive-not-recognized). If you still have issues, please contact me.
