### ISSUE TITLE
Support disc number field

### ISSUE THREAD

**Issue by bluecar112** [MoleMan1024/audiowagon#62]
Have a huge number of multi cd albums (Grateful Dead!) that have been ripped to flac with encoded disc number and track number (within the disc it appears on) that sort as expected on Sonos and other players.  Currently Audiowagon only sorts by track number resulting in all the track 1’s followed by the 2’s, etc. which disrupts the flow of concert albums.

Request that multi cd albums with embedded disc number tag be supported when sorting.

Thanks and regards

**Comment by MoleMan1024** [comment]
Will be in version 2.0.0
