### ISSUE TITLE
Playlists don't work when using relative parent path traversal

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#65]
received from a user via e-mail:

My playlists are currently in m3u format and my files are arranged like this on my storage device:

---
\Music\<various_sub_folders>\<various_mp3_files>
\Playlists\<various_sub_folders>\<various_m3u_files>
\Podcasts\<various_sub_folders>\<various_m3u_files>
---

The playlist entries look like this (utf-8 encoded, Windows-style line endings, and back-slash directory separators):
..\Music\subfolderA1\subfolderA2\track1.mp3
..\Music\subfolderB1\subfolderB2\track2.mp3
..\Podcasts\subfolderC\track3.mp3
...

This worked in my previous car, but AudioWagon fails to find the audio files. The audio files play fine when selected directly, but cannot be played from the playlist.
I include the leading ".." assuming that the track should be located relative to the folder containing the playlist file (i.e. it needs to traverse up one level to the root from the "Playlists" folder before traversing into the Music folder).

**Comment by micksmothers** [comment]
I had this same issue - I worked around it by moving my playlists to the root folder and it now works, but I'll put them back into my similar structure that the original person had. BTW, is there support for .pls or only .m3u?
