### ISSUE TITLE
USB drives no longer detected with car version 2.0 / Android Automotive 11

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#68]
by e-mail from two users: USB drives are no longer detected with Volvo/Polestar version 2.0 (Android Automotive 11).

-------

Please see info on this [on the homepage](https://moleman1024.github.io/audiowagon/#-2022-04-06--important-message)

**Comment by MoleMan1024** [comment]
Cannot reproduce this yet since I don't have that version in my car.
Will try to compile AAOS 12 for phone and try if reproducible there, but might behave differently than in the car.
Added hidden TextView to show logfile on screen to maybe see what is going on.
If this was intentional by Volvo/Polestar this might mean the end of the app but let'see first...

**Comment by lvitalis** [comment]
Please tell me it's an april fools joke ?

**Comment by agdejager** [comment]
Please tell me it's an april fools joke ? Is It????

**Comment by MoleMan1024** [comment]
No it is not.

**Comment by MoleMan1024** [comment]
Tried AAOS 12 on Pixel 3 XL: GUI scale is messed up, changing density in BoardConfig.mk does not help, cannot click on anything properly, will try a AAOS 11 build instead.

**Comment by MoleMan1024** [comment]
Released a version 1.5.6 that allows to show the logfile on screen via AudioWagon Settings > tap on "Version" field (because log files can't be written to USB when USB does not work). Maybe there is an error message in there...

**Comment by TomKario** [comment]
I just sent some photos. I desperately hope he's able to fix it.

**Comment by TomKario** [comment]
What 'Feinhessisch' wants to say is that Volvo cut off the data connection of the USB bus. If this is intentionally or a bug ist not known. Maybe we have to wait until June, then the new release will come which should support carplay and such things.

**Comment by agdejager** [comment]
> What 'Feinhessisch' wants to say is that Volvo cut off the data connection of the USB bus. If this is intentionally or a bug ist not known. Maybe we have to wait until June, then the new release will come which should support carplay and such things.

Not acceptable!!!

**Comment by IcyT** [comment]
> So what... if acceptable or not you can't change this! This sucks, you're right, so don't get a Volvo or polestar and deal with other model problems.

That was a useless comment. What about the people who have a Volvo or Polestar already?
And in my opinion we can change this. If we're loud enough together, they will change it. If AudioWagon would not have existed, I would not have bought a PS2 indeed. So for me this makes all of the difference and I will complain. Many times. And so should everybody who wants to have that back.

**Comment by TomKario** [comment]
@IcyT Jepp, unfortunately you're right, mine was the second useless comment here. Sorry for that.
But this is not the right place to complain. Complaining here does not reach Volvo.
I'm one of two who reported the problem and I'm in contact with MoleMan by mail and sent him pics of the log to investigate what's going on. Also I'm in contact with Volvo because my XC60 T6 Recharge Model 22 got V2.0 with Android11 about two weeks ago. So let's stop crying here, shout out loud on more useful platforms. Let's concentrate on the solution if there is any.

**Comment by micksmothers** [comment]
Once I get 2.0 OTA I'll check as well.

**Comment by Dream-Rider** [comment]
Annoyed at the disabling of the only way we could playback 16bit audio...its astonishing really, particularly with such a great hifi system! I have written to Volvo about this and would encourage all the others this effects to write in too please.

**Comment by lvitalis** [comment]
I complained on Facebook and Polestar answered after a couple of days (they probably did not know the answer and had to ask Google)

> The latest update (P2.0) introduces the latest Android Automotive OS to Polestar 2 (Android R). This has temporarily limited the functionality available from the USB-C port in preparation for future functionality. This change is expected to be updated in the next software update (P2.1) and we apologise for the inconvenience in the interim.

Notice the words "temporarily" and "interim". At least there is hope.

**Comment by MoleMan1024** [comment]
This has been fixed by Volvo/Polestar with car version 2.2.
