### ISSUE TITLE
Album art not showing for tracks in now playing list when playing a playlist

### ISSUE THREAD

**Issue by RandomGithubUsername** [MoleMan1024/audiowagon#71]
**Describe the issue**
Album art not showing for tracks in now playing list when playing a playlist, even after indexing is complete. Album art shows up fine if played from an album or track directly though.

**To Reproduce**
1. Select any (valid) playlist (.m3u) with more than 1 track in it from files view.
2. Tap the now playing list icon 
3. Notice that album art not displayed for any of the tracks.

**Expected behavior**
Album art should be displayed even when played from playlist similar to playing an album.

**AudioWagon version**
2.0.0

**Car version**
Volvo XC40

**Comment by MoleMan1024** [comment]
@RandomGithubUsername : could you provide a log file? https://moleman1024.github.io/audiowagon/#how-do-i-report-an-issue  You can just drag&drop it into this comment box to attach it.

**Comment by MoleMan1024** [comment]
no more info from issue opener since >3 weeks, closing as not reproducible
