### ISSUE TITLE
Play music from cloud storage

### ISSUE THREAD

**Issue by sparkdreamstudio** [MoleMan1024/audiowagon#72]
As a Volvo car owner, 
I do not know when will the 2.2 updates released and whether USB external feature would be lifted again in the future.
I think it would be great if this app could play music from cloud storage(like google drive, ms one drive, or dropbox).

**Comment by MoleMan1024** [comment]
It is very unlikely I will implement this, feels like a lot of work.

**Comment by sparkdreamstudio** [comment]
> It is very unlikely I will implement this, feels like a lot of work and it is against the focus of the app (play locally).

I see. I wished I could help you. Unfortunately, I am an iOS developer. 😵‍💫

**Comment by sparkdreamstudio** [comment]
Not in plan

**Comment by sparkdreamstudio** [comment]
Not in plan
