### ISSUE TITLE
"Fehler USB Stick" with 2.2 Update 

### ISSUE THREAD

**Issue by TarikBe** [MoleMan1024/audiowagon#73]
Hello, 

with the new Update to 2.2 Audio Wagon works again (finally!) but there is a new Message that appears that can be ignored to continue (Stick ist formatted with FAT32):

![image](https://user-images.githubusercontent.com/90717748/176997516-771b132c-cb6d-4533-92b0-912eb53fad3e.png)

**Comment by MoleMan1024** [comment]
This issue is triggered by a new Polestar system app "USB status <something>". When you force stop this app and plug in a USB drive this warning will not appear until next reboot. Has nothing to do with my app, please ask Polestar to fix this.

**Comment by vlast3k** [comment]
I get it as well on a XC60 B4 with 2.2 firmware. I just tried one Blitzwolf USB though, i need to try more. I thought everybody gets it and just lives with it.
For some reason always i have to approve access to the USB, regardless of whether it have checked the checkbox or not
