### ISSUE TITLE
Permission popup does not show when switching to reverse camera during startup

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#76]
**Describe the issue**
Received via e-mail: when switching to reversing camera during startup of infotainment the AudioWagon permission popup does not appear.

**To Reproduce**
- unlock and enter car
- switch to reverse right away while Android is starting up
- will show camera screen
- usually AudioWagon popup would appear but only the new Volvo/Polestar "USB not supported" popup appears

**Expected behavior**
- should show permission popup

**AudioWagon version**
2.1.1

**Car version**
P2.2

**Logfiles**
```
2022-07-19 15:24:45.818 [DEBUG   ][21561][USBDevPerm          ] USB device permission updated to DENIED for: class de.moleman1024.audiowagon.filestorage.usb.USBMediaDevice{Verbatim STORE N GO(6309;579;/dev/bus/usb/001/105;-1045548105)}
```

**Comment by micksmothers** [comment]
I can verify this happens as well. I have to remove and reinsert the USB stick to get the prompts back again (workaround). I suppose I could probably force kill AudioWagon and restart it to get the same outcome. Better yet, I just dismiss both prompts before I engage reverse. Anyway, just a confirmation of the behavior.

**Comment by MoleMan1024** [comment]
In version 2.2.1 you can re-trigger the permission popup by entering the AudioWagon settings.
