### ISSUE TITLE
When switching playlist in shuffle mode, the same track always plays first

### ISSUE THREAD

**Issue by bondms** [MoleMan1024/audiowagon#83]
**Describe the issue**
When shuffle mode is enabled, switching to a different playlist queues the tracks of that playlist randomly with the exception of the first track which is always the same.

**To Reproduce**
The issue can be reliably reproduced.
1. Enable shuffle.
2. Select a playlist file. Note the first track.
3. Select a different playlist file. Note the first track.
4. Select the first playlist file again. Note the first track is the same as for step 2.
5. Select the second playlist file again. Note the first track is the same as for step 3.

**Expected behavior**
All the tracks should be shuffled, including the first one.

**AudioWagon version**
2.0.1

**Car version**
P2.2

**Logfiles**
I believe this issue is easily reproducible. If it's not then please request log files and I will provide them.

**Photos / Video**
If the description is not clear then please request clarification and I will provide photos and/or a video.

**Comment by MoleMan1024** [comment]
This behaviour is intentional. You don't want your currently playing track to be changed

**Comment by MoleMan1024** [comment]
Ah hold on, you mean when you initially start playing the playlist this also happens? That is not intentional.
I just tried it and can confirm it.
The idea with shuffle mode is to not modify the currently playing track. However when starting a new playback queue this also happens which is wrong. I will look into it.

**Comment by MoleMan1024** [comment]
This is fixed in version 2.2.1

**Comment by MoleMan1024** [comment]
The fix for this was only applied for tracks in an album, but not for playlists nor for all tracks for an artist. I will make another change.
