### ISSUE TITLE
Add folder to play queue

### ISSUE THREAD

**Issue by Riven-Spell** [MoleMan1024/audiowagon#86]
As a car driver, I want to be able to target one or more directories to add to the play queue so that I can mix between multiple artists at once easily, without creating a `m3u8` playlist on my computer.

**Comment by MoleMan1024** [comment]
There is the "Play all" function but it is only for the current directories or subdirectories. For everything else you need to create a playlist. There is limited things I can do with the GUI, I don't know how I would implement this.
