### ISSUE TITLE
Long time to swipe/scroll in file view

### ISSUE THREAD

**Issue by Ixstala** [MoleMan1024/audiowagon#87]
Is it possible to add a vertical scroll bar in the right hand side of file view? I have my music organized into folders by artist and it takes a long time to swipe down to the desired folder (my wife's preferred method!). A scroll bar or quick sort/filter by first letter would be awesome to manage this easier.

Awesome app by the way! Saved my music experience in the C40 Recharge!

**Comment by MoleMan1024** [comment]
hi,
sorry the GUI is mostly controlled by Android Automotive, I only provide the data for playing back the music, you have to go to Volvo or Polestar to request something like that.

You can use the search function or use voice commands though.
