### ISSUE TITLE
When playing an album and it finished, it does not automatically go to the next album

### ISSUE THREAD

**Issue by XC60-Driver** [MoleMan1024/audiowagon#90]
**Describe the issue**
When listening to an album and the last track is playing, after it finishes it does not continue to the next album  on the USB stick

**To Reproduce**
When playing an album and it get to the last track it then displays an error and you then have to go back and choose a new album to play

**Expected behavior**
would like the next album to play

**AudioWagon version**
latest

**Car version**
MY22 XC60 2.3

**Comment by MoleMan1024** [comment]
@XC60-Driver : the behaviour depends on how you started the playback. Please describe how you started the playback or attach a log file. 
If you just select a single album to play, then AudioWagon will not continue with other albums, that is expected. If you instead select "play all" in the album list of an artist, it should play all albums of that artist.

**Comment by MoleMan1024** [comment]
No answer to my question for a month, closing ticket.
