### ISSUE TITLE
Volvo - Album Art Not Always Displayed

### ISSUE THREAD

**Issue by griff10000** [MoleMan1024/audiowagon#92]
SYSTEM DETAILS
------------------
Car: Volvo XC40, P8, early 2023 model.
Software: AudioWagon v 2.2.8 (2nd Nov 2022).
Storage: New 64 GB SanDisK flash drive with a reversible USB Type-C and a traditional Type-A connector. 
File System: Fat32.
Music Files: ~14 GB stored in album directories under top directory, 'Music'.

Problem: 
1) When starting AW the system displays: "USB Device Error, This USB is not supported", with the option to dismiss.
2) User then given the option to always open SanDisk USB, which I ticked.
3) Album art is rarely displayed. Sometimes displayed when half way through a track. No log file.

Good Points
-------------
1) Simple user interface
2) All controls appear to work as expected
3) Music quality is good

Many thanks for producing this music app.

Regards,

Graham

**Comment by MoleMan1024** [comment]
@griff10000 : please open one issue per ticket only. 
For point 1) this is a Polestar/Volvo issue, please check this [issue](https://github.com/MoleMan1024/audiowagon/issues/73)
For point 2) same, please check the [frequently asked questions](https://moleman1024.github.io/audiowagon/faq.html#why-does-the-permission-popup-appear-each-time-the-always-open-audiowagon--checkbox-does-not-do-anything)
For point 3) please provide a log file, I cannot analyze this without a log file. You can drag and drop file attachments into this "write" box

**Comment by Claudi0C** [comment]
The same thing happens to me as described in point 3) after upgrading to AudioWagon 2.2.8. Before the update album arts were working properly.
My car is Volvo V60 2023 and the car's software version is 2.4.
As soon as possible I will post a log file.

Also from me many thanks for developing this app.

Regards,
Claudio

**Comment by MoleMan1024** [comment]
hi @Claudi0C : ok, thanks for letting me know. I did change [something](https://github.com/MoleMan1024/audiowagon/blob/master/CHANGELOG.md#228---2022-11-05) regarding album art in 2.2.8, so maybe there is a problem with that. 
After upgrading to 2.2.8 did you ever restart the Android headunit (for example by holding the bottom horizontal button for > 30 seconds or leaving the car locked and unused for multiple days)?

**Comment by griff10000** [comment]
I had the log file creation switched off. I have just switched it on and played around with AW for a while - log attached.
[audiowagon_2022-11-25_07-57-19.log](https://github.com/MoleMan1024/audiowagon/files/10089762/audiowagon_2022-11-25_07-57-19.log)

Interesting behaviour observed: 
1. Select track to play - no album art, 
2. Select next track by clicking on forward arrow - no album art displayed,
3. Switch back by clicking on back arrow - album art displayed correctly for track in in item (1). 
This is repeatable.

Hope this helps

Regards,
Graham

**Comment by Claudi0C** [comment]
> hi @Claudi0C : ok, thanks for letting me know. I did change [something](https://github.com/MoleMan1024/audiowagon/blob/master/CHANGELOG.md#228---2022-11-05) regarding album art in 2.2.8, so maybe there is a problem with that. After upgrading to 2.2.8 did you ever restart the Android headunit (for example by holding the bottom horizontal button for > 30 seconds or leaving the car locked and unused for multiple days)?

Yes, after the update I did the Android headunit restart, but the situation did not improve, I still do not see album arts.

**Comment by Claudi0C** [comment]
> Interesting behaviour observed:
> 
>     1. Select track to play - no album art,
> 
>     2. Select next track by clicking on forward arrow - no album art displayed,
> 
>     3. Switch back by clicking on back arrow - album art displayed correctly for track in in item (1).
>        This is repeatable.

I confirm, I also observed the same behavior, and the same thing happens by switching to the previous track on point 2.
Another thing I have observed is that album arts show up partially in the album list, meaning that they show up only for some albums.

Regards,
Claudio

**Comment by griff10000** [comment]
Thanks Cludio,

I have never seen album art in the album list.

By the way, I saw a comment on a Volvo forum saying that album art images can only be 500 x 500 max. So I went through mine and made sure that none of my album art exceeded this.

Regards,
Graham

**Comment by Claudi0C** [comment]
> I have never seen album art in the album list.
> 
> By the way, I saw a comment on a Volvo forum saying that album art images can only be 500 x 500 max. So I went through mine and made sure that none of my album art exceeded this.

That's good to know.
In the version of the app prior to 2.2.8, album arts were showing perfectly for all albums, regardless of the size of the image (in some cases I have images that exceed 500x500 in size).

Regards,
Claudio

**Comment by MoleMan1024** [comment]
Thanks for the info. I can reproduce this issue in my own car. I will look into it.

**Comment by MoleMan1024** [comment]
This should be fixed in v2.3.1
