### ISSUE TITLE
Support for self hosted streaming servers?

### ISSUE THREAD

**Issue by litebito** [MoleMan1024/audiowagon#93]
Please describe the feature you would like to see, for example in the form of a user story:

As a Volvo Car driver, 
I would like to ask if you are willing to support self hosted streaming servers  (those which implement subsonic API v1.13 or higher, like for example subsonic forks such as [airsonic](https://airsonic.github.io/), [madsonic](https://www.madsonic.org/), [Navidrome](https://www.navidrome.org/), [Ampache](https://ampache.org/)
so that we don't need to keep syncing, copying, move around USB storage devices, and work around USB device incompatibilities with car systems.

I understand this is a major change, and very different then reading from an USB storage device.
Just wanted to check if it can be considered or not at all.

**Comment by MoleMan1024** [comment]
hi, sorry that is basically a completely new app. I can't support that.

**Comment by litebito** [comment]
Ok thanks, no problem. Just looking around to who would be able to do so.
