### ISSUE TITLE
Unknown Error for large or high bitrate m4a files (?)

### ISSUE THREAD

**Issue by litebito** [MoleMan1024/audiowagon#94]
**Describe the issue**
I get quite a few "Unknown error" messages on a decent amount of *.m4a audio files. After trying to narrow it down a little bit more, it seems to happen with bigger audio files OR with a very high bitrate. So far of all the audio files I tried for testing :
- files > 24MB or a bitrate > 1000(vbr) seem to give the error
- files of <= 12MB and/or a bitrate <= 320 are playing fine.

I've not yet been able to exclude high bitrate small files, or low bitrate big files, but I will continue to test while I'm trying to find files > 24MB with a bitrate <= 320 in my collection

**To Reproduce**
See above

**Expected behavior**
No errors during playback of m4a files

**AudioWagon version**
v2.2.8

**Car version**
Volvo XC60 T6 eAWD with Software v2.4

**Logfiles**
[audiowagon_2022-11-23_17-42-23.log](https://github.com/MoleMan1024/audiowagon/files/10077972/audiowagon_2022-11-23_17-42-23.log)

**Comment by litebito** [comment]
I can provide 2 sample audio files which fail to play in AudioWagon:
https://www.dropbox.com/sh/3y21jxl1r4mytzf/AABKnWOgojsLoQowJTAyI49Ha?dl=0
(link expires 30-nov-2022)

**Comment by MoleMan1024** [comment]
Thanks for the details. I had a look at the audio files, opening them in VLC shows that they use the *Apple Lossless Audio Codec (alac)* which it looks like Android [does not support](https://developer.android.com/guide/topics/media/media-formats).

I will check if I can detect this situation and show a better error message.

**Comment by litebito** [comment]
Aha, interesting, because I chose "FLAC" in my media tool to convert them. so I've to check what is really happening there. (And sadly, I've hundreds of files like this)
So I guess AudioWagon does not use a media codec directly.
Maybe you also can add to your FAQ that ALAC is not supported?

**Comment by MoleMan1024** [comment]
The error message is improved in v2.3.1
